openapi: 3.0.3
info:
  title: API Gateway
  description: API Gateway for microservices architecture
  version: 1.0.0
  
servers:
  - url: /api/v1
    description: Base API path

tags:
  - name: auth
    description: Authentication operations
  - name: users
    description: User management operations
  - name: promos
    description: Promotion code operations

paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Register a new user
      description: Create a new user account with login, password and email
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /auth/login:
    post:
      tags:
        - auth
      summary: Authenticate user
      description: Login with username and password
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /promos:
    post:
      tags:
        - promos
      summary: Create a new promo code
      description: Create a new promotion code
      operationId: createPromo
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoCreate'
      responses:
        '201':
          description: Promo code successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    get:
      tags:
        - promos
      summary: Get paginated list of promo codes
      description: Retrieve a paginated list of promotion codes
      operationId: getPromos
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: List of promo codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /promos/{id}:
    get:
      tags:
        - promos
      summary: Get promo code by ID
      description: Retrieve a specific promotion code by its ID
      operationId: getPromoById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Promo code ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Promo code details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Promo code not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    put:
      tags:
        - promos
      summary: Update promo code
      description: Update an existing promotion code
      operationId: updatePromo
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Promo code ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PromoUpdate'
      responses:
        '200':
          description: Promo code successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromoResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Promo code not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      tags:
        - promos
      summary: Delete promo code
      description: Delete an existing promotion code
      operationId: deletePromo
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: Promo code ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Promo code successfully deleted
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Promo code not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserRegistration:
      type: object
      required:
        - login
        - password
        - email
      properties:
        login:
          type: string
          description: User login name
          example: "john_doe"
        password:
          type: string
          format: password
          description: User password
          example: "SecureP@ssw0rd"
        email:
          type: string
          format: email
          description: User email address
          example: "john.doe@example.com"
    
    UserLogin:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          description: User login name
          example: "john_doe"
        password:
          type: string
          format: password
          description: User password
          example: "SecureP@ssw0rd"
    
    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: User unique identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        login:
          type: string
          description: User login name
          example: "john_doe"
        email:
          type: string
          format: email
          description: User email address
          example: "john.doe@example.com"
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2023-01-01T12:00:00Z"
    
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT authentication token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjNlNDU2Ny1lODliLTEyZDMtYTQ1Ni00MjY2MTQxNzQwMDAiLCJleHAiOjE2MTY3NjY5MDB9.8Iy6iFPYXaCt_DO6hBQ8DNlVHJ9RJcFD-_6L5bDUEMM"
        expiresAt:
          type: string
          format: date-time
          description: Token expiration timestamp
          example: "2023-01-01T14:00:00Z"
        user:
          $ref: '#/components/schemas/UserResponse'
    
    PromoCreate:
      type: object
      required:
        - name
        - description
        - discountAmount
        - code
      properties:
        name:
          type: string
          description: Promotion name
          example: "Summer Sale"
        description:
          type: string
          description: Detailed description of the promotion
          example: "Special discount for summer season"
        discountAmount:
          type: number
          format: float
          description: Discount amount (percentage)
          example: 15.5
        code:
          type: string
          description: Unique promo code
          example: "SUMMER2023"
    
    PromoUpdate:
      type: object
      properties:
        name:
          type: string
          description: Promotion name
          example: "Summer Sale"
        description:
          type: string
          description: Detailed description of the promotion
          example: "Special discount for summer season"
        discountAmount:
          type: number
          format: float
          description: Discount amount (percentage)
          example: 15.5
        code:
          type: string
          description: Unique promo code
          example: "SUMMER2023"
    
    PromoResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Promo unique identifier
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          description: Promotion name
          example: "Summer Sale"
        description:
          type: string
          description: Detailed description of the promotion
          example: "Special discount for summer season"
        creatorId:
          type: string
          format: uuid
          description: ID of the user who created the promo
          example: "123e4567-e89b-12d3-a456-426614174000"
        discountAmount:
          type: number
          format: float
          description: Discount amount (percentage)
          example: 15.5
        code:
          type: string
          description: Unique promo code
          example: "SUMMER2023"
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2023-01-01T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2023-01-01T14:00:00Z"
    
    PromoList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PromoResponse'
        total:
          type: integer
          description: Total number of items
          example: 100
        page:
          type: integer
          description: Current page number
          example: 1
        limit:
          type: integer
          description: Number of items per page
          example: 10
        pages:
          type: integer
          description: Total number of pages
          example: 10
    
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP status code
          example: 400
        message:
          type: string
          description: Error message
          example: "Bad request"
        details:
          type: array
          items:
            type: string
          description: Detailed error information
          example: ["Password must be at least 8 characters long"]
